In [1]:
import pandas as pd
import numpy as np

In [3]:
# Load Data
df = pd.read_csv("Sample_data.csv")
df

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,Government,Germany,Carretera,None,1513.0,3,350,529550.0,0.00,529550.00,393380.0,136170.00,1-Dec-14,12,December,2014
1,Government,Germany,Paseo,None,1006.0,10,350,352100.0,0.00,352100.00,261560.0,90540.00,1-Jun-14,6,June,2014
2,Government,Canada,Paseo,None,1725.0,10,350,603750.0,0.00,603750.00,448500.0,155250.00,1-Nov-13,11,November,2013
3,Government,Germany,Paseo,None,1513.0,10,350,529550.0,0.00,529550.00,393380.0,136170.00,1-Dec-14,12,December,2014
4,Government,Germany,Velo,None,1006.0,120,350,352100.0,0.00,352100.00,261560.0,90540.00,1-Jun-14,6,June,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,Midmarket,Canada,Paseo,High,1614.0,10,15,24210.0,3631.50,20578.50,16140.0,4438.50,1-Apr-14,4,April,2014
696,Midmarket,Canada,Paseo,High,2559.0,10,15,38385.0,5757.75,32627.25,25590.0,7037.25,1-Aug-14,8,August,2014
697,Enterprise,Germany,Paseo,High,1085.0,10,125,135625.0,20343.75,115281.25,130200.0,-14918.75,1-Oct-14,10,October,2014
698,Midmarket,Germany,Paseo,High,1175.0,10,15,17625.0,2643.75,14981.25,11750.0,3231.25,1-Oct-14,10,October,2014
699,Channel Partners,United States of America,Paseo,High,914.0,10,12,10968.0,1645.20,9322.80,2742.0,6580.80,1-Dec-14,12,December,2014

In [4]:
# Basic Info
print(df.shape)
df.info()

(700, 16)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 16 columns):
Segment                700 non-null object
Country                700 non-null object
Product                700 non-null object
Discount Band          700 non-null object
Units Sold             700 non-null float64
Manufacturing Price    700 non-null int64
Sale Price             700 non-null int64
Gross Sales            700 non-null float64
Discounts              700 non-null float64
 Sales                 700 non-null float64
COGS                   700 non-null float64
Profit                 700 non-null float64
Date                   700 non-null object
Month Number           700 non-null int64
Month Name             700 non-null object
Year                   700 non-null int64
dtypes: float64(6), int64(4), object(6)
memory usage: 71.2+ KB

In [5]:
# Clean column names
df.columns = df.columns.str.strip()
print(df.columns.tolist())

['Segment', 'Country', 'Product', 'Discount Band', 'Units Sold', 'Manufacturing Price', 'Sale Price', 'Gross Sales', 'Discounts', 'Sales', 'COGS', 'Profit', 'Date', 'Month Number', 'Month Name', 'Year']

In [6]:
# Check nulls & duplicates
print(df.isnull().sum())
print("Duplicates:", df.duplicated().sum())

Segment                0
Country                0
Product                0
Discount Band          0
Units Sold             0
Manufacturing Price    0
Sale Price             0
Gross Sales            0
Discounts              0
Sales                  0
COGS                   0
Profit                 0
Date                   0
Month Number           0
Month Name             0
Year                   0
dtype: int64
Duplicates: 0

In [7]:
#Fix data types

df['Date'] = pd.to_datetime(df['Date'])

num_cols = ['Units Sold','Manufacturing Price','Sale Price','Gross Sales',
            'Discounts','Sales','COGS','Profit']
for col in num_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df.dtypes

Segment                        object
Country                        object
Product                        object
Discount Band                  object
Units Sold                    float64
Manufacturing Price             int64
Sale Price                      int64
Gross Sales                   float64
Discounts                     float64
Sales                         float64
COGS                          float64
Profit                        float64
Date                   datetime64[ns]
Month Number                    int64
Month Name                     object
Year                            int64
dtype: object

In [8]:
# Explore unique values
print(df['Segment'].unique())
print(df['Country'].unique())
print(df['Product'].unique())
print(df['Discount Band'].unique())

['Government' 'Midmarket' 'Channel Partners' 'Enterprise' 'Small Business']
['Germany' 'Canada' 'France' 'Mexico' 'United States of America']
['Carretera' 'Paseo' 'Velo' 'VTT' 'Amarilla' 'Montana']
['None' 'Low' 'Medium' 'High']

In [9]:
# Summary statistics
df.describe()

,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Month Number,Year
count,700.000000,700.000000,700.000000,7.000000e+02,700.000000,7.000000e+02,700.000000,700.000000,700.000000,700.000000
mean,1608.294286,96.477143,118.428571,1.827594e+05,13150.354629,1.696091e+05,145475.211429,24133.860371,7.900000,2013.750000
std,867.427859,108.602612,136.775515,2.542623e+05,22962.928775,2.367263e+05,203865.506118,42760.626563,3.377321,0.433322
min,200.000000,3.000000,7.000000,1.799000e+03,0.000000,1.655080e+03,918.000000,-40617.500000,1.000000,2013.000000
25%,905.000000,5.000000,12.000000,1.739175e+04,800.320000,1.592800e+04,7490.000000,2805.960000,5.750000,2013.750000
50%,1542.500000,10.000000,20.000000,3.798000e+04,2585.250000,3.554020e+04,22506.250000,9242.200000,9.000000,2014.000000
75%,2229.125000,250.000000,300.000000,2.790250e+05,15956.343750,2.610775e+05,245607.500000,22662.000000,10.250000,2014.000000
max,4492.500000,260.000000,350.000000,1.207500e+06,149677.500000,1.159200e+06,950625.000000,262200.000000,12.000000,2014.000000

In [11]:
# Save cleaned file
df.to_csv("cleaned_data.csv", index=False)